/**
 * @file dist.cpp
 * @brief Graph-based alignment and precision/recall evaluation implementations.
 */
#include <algorithm>
#include <cassert>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <map>
#include <queue>
#include <set>
#include <string>
#include <thread>
#include <utility>
#include <vector>

#include "cluster.h"
#include "dist.h"
#include "print.h"


/**
 * @brief Calculates the NG50 statistic from a list of phase block sizes and genome size.
 *
 * @param[in] phase_blocks List of phase block sizes.
 * @param[in] total_bases Sum total of all bases in the genome.
 * @return The minimum value for which the sum of phase blocks greater than this size account for
 *   more than 50% of total genome size, or 0 if less than 50% of the genome is phased.
 */
int calc_ng50(std::vector<int> phase_blocks, size_t total_bases) {
    size_t total_phased = 0;
    // sort blocks in descending order
    std::sort(phase_blocks.begin(), phase_blocks.end(), std::greater<>());
    // calculate running sum, return once 50% of genome size is reached
    for (size_t i = 0; i < phase_blocks.size(); i++) {
        total_phased += phase_blocks[i];
        if (total_phased >= double(total_bases) / 2)
            return phase_blocks[i];
    }
    return 0;
}

/**************************************************************************************************/

/**
 * @brief Generates a haplotype sequence by applying a range of variants to the reference.
 *
 * @param[in] ref A pointer to an object containing the reference sequence.
 * @param[in] vars A pointer to the variants on this contig.
 * @param[in] ctg The name of the current contig.
 * @param[in] beg_idx The 0-based inclusive index of the first variant to include.
 * @param[in] end_idx The 0-based exclusive index of the last variant to include.
 * @param[in] beg_pos The 0-based inclusive index of the first reference base to include.
 * @param[in] end_pos The 0-based exclusive index of the last reference base to include.
 * @param[in] min_qual Skip variants with quality scores below this threshold.
 * @return The sequence generated by applying the selected variants to the reference sequence.
 * @throws ERROR if the next reference segment ends before the current reference position.
 * @throws ERROR if the contig is not present in the reference FASTA.
 * @throws ERROR if the reference position lies outside the contig.
 */
std::string generate_str(
        std::shared_ptr<fastaData> ref, 
        std::shared_ptr<ctgVariants> vars, const std::string & ctg,
        int beg_idx, int end_idx, int beg_pos, int end_pos, 
        int min_qual /* = 0 */) {

    int var_idx = beg_idx;
    std::string str = "";
    while (var_idx < vars->n && vars->poss[var_idx] < beg_pos) var_idx++;
    for (int ref_pos = beg_pos; ref_pos < end_pos; ) {

        // VARIANT
        if (var_idx < end_idx && ref_pos == vars->poss[var_idx]) {
            if (vars->var_quals[var_idx] >= min_qual) {
                switch (vars->types[var_idx]) {
                    case TYPE_INS:
                        str += vars->alts[var_idx];
                        break;
                    case TYPE_DEL:
                        ref_pos += vars->refs[var_idx].size();
                        break;
                    case TYPE_SUB:
                        str += vars->alts[var_idx];
                        ref_pos++;
                        break;
                    case TYPE_CPX:
                        str += vars->alts[var_idx];
                        ref_pos += vars->refs[var_idx].size();
                        break;
                    case TYPE_REF: // not a stored variant type, so nothing to consume
                        break;
                }
            }
            var_idx++; // next variant

        } else { // NO VARIANT
            // add entire ref seq up to next variant or region end
            int ref_end = (var_idx < end_idx) ?
                std::min(end_pos, vars->poss[var_idx]) : end_pos;
            if (ref_end < ref_pos) {
                printf("ref_pos:%d ref_end:%d beg_pos: %d end_pos: %d\n",
                        ref_pos, ref_end, beg_pos, end_pos);
                for(int i = beg_idx; i < end_idx; i++) {
                    printf("%s:%d %s -> %s\n", ctg.data(), vars->poss[i],
                            vars->refs[i].data(), vars->alts[i].data());
                }
                ERROR("No variant, but ref_end < ref_pos (generate_str)");
            }
            // check both failure modes separately, so neither is reported as the other (#167)
            if (ref->fasta.find(ctg) == ref->fasta.end())
                ERROR("Contig '%s' not in reference FASTA (generate_str)", ctg.data());
            const std::string & ref_seq = ref->fasta.at(ctg);
            if (ref_pos < 0 || ref_pos > int(ref_seq.size()))
                ERROR("Position %d out of range on contig '%s' of length %d (generate_str)",
                        ref_pos, ctg.data(), int(ref_seq.size()));
            str += ref_seq.substr(ref_pos, ref_end-ref_pos);
            ref_pos = ref_end;
        }
    }
    return str;
}

/**************************************************************************************************/

/**
 * @brief Runs graph-based alignment and returns the optimal alignment score.
 *
 * Performs a forward-pass weighted shortest-path alignment (Dijkstra over a binary-heap priority
 * queue, ordered by true fractional cost) between the truth sequence and the query graph, filling a
 * pointer map used for backtracking the optimal path.
 *
 * @param[in] graph The alignment graph containing query and truth nodes.
 * @param[in,out] ptrs Map populated with predecessor pointers for backtracking.
 * @param[in] print Whether to enable debug printing.
 * @return The optimal alignment cost, rounded up to an integer.
 * @throws ERROR if the queue drains before the endpoint cell is reached.
 */
int calc_prec_recall_aln(
        const std::shared_ptr<Graph> graph,
        std::unordered_map<idx4, idx4> & ptrs,
        bool print
        ) {

    // Dijkstra on fractional cost: a bypass edge costs the exact (1-ct)*len, so the queue orders
    // paths by true cost and a cheaper bypass simply wins. All edge costs are non-negative.
    std::unordered_set<idx4> done;         // finalized cells (true-cost-optimal)
    std::unordered_map<idx4, double> best; // best known true cost per cell

    // un-rounded toll for transitioning INTO truth node tni: (1-ct)*len on a bypass node
    auto tni_skip_toll = [&](int tni) -> double {
        if (graph->tskips[tni] < 0) return 0.0;
        std::shared_ptr<ctgVariants> tvars = graph->sc->callset_vars[TRUTH];
        int vidx = graph->tskips[tni];
        int len = std::max(int(tvars->refs[vidx].size()), int(tvars->alts[vidx].size()));
        return (1.0 - g.credit_threshold) * len;
    };

    // one candidate path to cell `to`, arriving from cell `from` at cumulative cost `cost`
    struct qentry { double cost; idx4 to; idx4 from; };
    // orders the queue cheapest-cost-first (std::priority_queue pops its largest element)
    struct qcmp { bool operator()(const qentry & a, const qentry & b) const { return a.cost > b.cost; } };
    std::priority_queue<qentry, std::vector<qentry>, qcmp> pq;

    // node 0 of each side is always reference (a left flank, or the zero-width entry node the Graph
    // constructor substitutes at reference position 0), so this fixed origin cell is never a variant
    idx4 start(0, 0, 0, 0);
    pq.push({0.0, start, idx4(0, 0, -1, -1)});
    best[start] = 0.0;

    // queue the edge into cell `to` via `from`, unless a cheaper path to `to` is already known
    auto push_if_cheaper = [&](const idx4 & to, const idx4 & from, double cost) {
        auto it = best.find(to);
        if (it == best.end() || cost < it->second - EPSILON) {
            best[to] = cost;
            pq.push({cost, to, from});
        }
    };

    idx4 end = idx4(graph->qnodes-1, graph->tnodes-1,
                int(graph->qseqs[graph->qnodes-1].length()-1),
                int(graph->tseqs[graph->tnodes-1].length()-1));

    double final_cost = -1.0;
    while (!pq.empty()) {
        qentry item = pq.top(); pq.pop();
        idx4 x = item.to;
        if (contains(done, x)) continue; // stale heap entry (lazy deletion)
        done.insert(x);
        ptrs[x] = item.from; // predecessor on the true-cost-optimal path
        double c = item.cost;

        // reached the endpoint: its cost is now finalized and optimal
        if (x == end) { final_cost = c; break; }

        // COST-0: match on query (diagonal extension to its maximum reach)
        idx4 y(x.qni, x.tni, x.qi, x.ti);
        bool match = false;
        while (y.qi+1 < int(graph->qseqs[y.qni].length()) &&
               y.ti+1 < int(graph->tseqs[y.tni].length()) &&
               graph->qseqs[y.qni][y.qi+1] == graph->tseqs[y.tni][y.ti+1]) {
            y.qi++;
            y.ti++;
            match = true;
        }
        if (match) push_if_cheaper(y, x, c);

        // bottom-right corner moves diagonally into next truth and query nodes (toll on bypass)
        if (x.qi == int(graph->qseqs[x.qni].length())-1 && x.ti == int(graph->tseqs[x.tni].length())-1) {
            for (int qni : graph->qnexts[x.qni]) {
                for (int tni : graph->tnexts[x.tni]) {
                    push_if_cheaper(idx4(qni, tni, 0, 0), x, c + tni_skip_toll(tni));
                }
            }
        }

        // last row moves into first row of all next query nodes (tni unchanged: no toll)
        if (x.qi == int(graph->qseqs[x.qni].length())-1 && x.ti < int(graph->tseqs[x.tni].length())) {
            for (int qni : graph->qnexts[x.qni]) {
                push_if_cheaper(idx4(qni, x.tni, 0, x.ti), x, c);
            }
        }

        // last col moves into first col of next truth node (toll on bypass)
        if (x.ti == int(graph->tseqs[x.tni].length())-1 && x.qi < int(graph->qseqs[x.qni].length())) {
            for (int tni : graph->tnexts[x.tni]) {
                push_if_cheaper(idx4(x.qni, tni, x.qi, 0), x, c + tni_skip_toll(tni));
            }
        }

        // COST-1 EDITS
        if (x.qi+1 < int(graph->qseqs[x.qni].length())) { // INS
            push_if_cheaper(idx4(x.qni, x.tni, x.qi+1, x.ti), x, c + 1.0);
        }
        if (x.ti+1 < int(graph->tseqs[x.tni].length())) { // DEL
            push_if_cheaper(idx4(x.qni, x.tni, x.qi, x.ti+1), x, c + 1.0);
        }
        if (x.qi+1 < int(graph->qseqs[x.qni].length()) &&
                x.ti+1 < int(graph->tseqs[x.tni].length())) { // SUB
            push_if_cheaper(idx4(x.qni, x.tni, x.qi+1, x.ti+1), x, c + 1.0);
        }
    }

    if (final_cost < 0) ERROR("Endpoint unreachable in 'calc_prec_recall_aln()'.");

    if (print) {
        printf("Alignment score: %f\n", final_cost);
        printf("Alignment:\n");
        print_graph_ptrs(graph, ptrs);
    }

    return int(std::ceil(final_cost - EPSILON));
}

/**************************************************************************************************/

/**
 * @brief Evaluates query variants against truth for one supercluster and haplotype combination.
 *
 * Builds the alignment graph, computes the single precision-recall alignment, and classifies every
 * variant as TP/FP/FN in one pass. The graph places each truth variant's reference-allele bypass
 * node in parallel with its alt node, so a truth variant the query failed to match within the
 * (1-ct)*len bypass-toll budget is routed around and labeled FN by the same backtrack that credits
 * the rest; no re-alignment is required.
 *
 * @param[in] scs Supercluster data containing query and truth variant containers.
 * @param[in] sc_idx Index of the supercluster to evaluate.
 * @param[in] ref Reference FASTA data.
 * @param[in] ctg Contig name.
 * @param[in] truth_hi Truth haplotype index (0 or 1).
 * @param[in] print Whether to enable debug printing.
 */
void evaluate_variants(std::shared_ptr<ctgSuperclusters> scs, int sc_idx,
			std::shared_ptr<fastaData> ref, const std::string & ctg, hap_t truth_hi, bool print) {
    std::shared_ptr<Graph> graph(new Graph(scs, sc_idx, ref, ctg, truth_hi));
    if (print) graph->print();

    // single alignment + backtrack: labels TP/FP and marks missed truth variants FN
    std::unordered_map<idx4, idx4> ptrs;
    calc_prec_recall_aln(graph, ptrs, print);
    calc_prec_recall(graph, ptrs, truth_hi, print);
}

/**************************************************************************************************/

/**
 * @brief Assigns TP/FP/FN error types and credit scores to variants from an alignment.
 *
 * Backtracks through the pointer map produced by calc_prec_recall_aln() to identify sync
 * groups and compute per-variant edit distance credit relative to the reference. A truth variant
 * whose reference-allele bypass node lies on the path is labeled a false negative, and each bypass
 * region acts as a hard sync-group boundary excluded from all credit computation, so no credit span
 * ever includes a bypassed (off-path) alt. The graph forces every truth variant onto the path via
 * either its alt node (labeled here) or its reference-allele bypass node (false negative), so the
 * trace labels every truth variant; none is left unlabeled.
 *
 * Each matched variant also records the other callset's genotype in its calc_gt: a query variant
 * gains the truth haplotype it matched, and a truth variant the haplotypes its matching query
 * variants were called on.
 *
 * @param[in] graph The alignment graph used during the forward pass.
 * @param[in] ptrs Predecessor pointer map from calc_prec_recall_aln().
 * @param[in] truth_hap Truth haplotype index (0 or 1).
 * @param[in] print Whether to enable debug printing.
 */
void calc_prec_recall(
        const std::shared_ptr<Graph> graph,
        const std::unordered_map<idx4, idx4> & ptrs,
        hap_t truth_hap, bool print
        ) {
    idx4 end(graph->qnodes-1, graph->tnodes-1,
            graph->qseqs[graph->qnodes-1].length()-1,
            graph->tseqs[graph->tnodes-1].length()-1);
    idx4 curr = end;
    int prev_query_ref_pos = graph->ref.size();
    int prev_truth_pos = graph->truth.size();
    int sync_group = 0;
    int query_dist = 0;
    std::vector<int> sync_tvars;
    std::vector<int> sync_qvars;

    // Bypassed-variant spans excised from the current group's credit measurement: reference
    // intervals [beg, end) and the matching this->truth intervals holding the off-path alt.
    std::vector< std::pair<int,int> > excised_ref;
    std::vector< std::pair<int,int> > excised_truth;
    size_t qvars_before_bypass = 0; ///< sync_qvars size on entering a bypass, to drop calls inside it
    std::shared_ptr<ctgVariants> qvars = graph->sc->callset_vars[QUERY];
    std::shared_ptr<ctgVariants> tvars = graph->sc->callset_vars[TRUTH];

    // all query variants default to FP unless path chosen
    for (int qni = 0; qni < graph->qnodes; qni++) {
        if (graph->qtypes[qni] != TYPE_REF) {
            int qvar_idx = graph->qidxs[qni];
            qvars->errtypes[truth_hap][qvar_idx] = ERRTYPE_FP;
            qvars->callq[truth_hap][qvar_idx] = qvars->var_quals[qvar_idx];
        }
    }

    // Returns s[lo, hi) with every interval in `cut` removed. `cut` intervals are disjoint and
    // recorded high-to-low by the backtrack, so they are sorted ascending before splicing.
    auto splice_out = [](const std::string & s, int lo, int hi,
            std::vector<std::pair<int,int>> cut) -> std::string {
        std::sort(cut.begin(), cut.end());
        std::string out;
        int pos = lo;
        for (const auto & c : cut) {
            int a = std::max(c.first, lo), b = std::min(c.second, hi);
            if (b <= a) continue; // interval lies outside this span
            if (a > pos) out += s.substr(pos, a - pos);
            pos = std::max(pos, b);
        }
        if (hi > pos) out += s.substr(pos, hi - pos);
        return out;
    };

    // Emit the accumulated sync group: compute its edit distance relative to reference over the
    // truth span [t_pos, prev_truth_pos) x ref span [q_ref_pos, prev_query_ref_pos), assign
    // TP/FP/FN credit to its query/truth variants, then reset the accumulators to (q_ref_pos,
    // t_pos). t_pos must be a valid this->truth offset (never derived from a bypass node).
    //
    // Any bypassed truth variant inside the span is excised from BOTH sides before measuring
    // ref_dist: its alt is present in this->truth but off-path, and the toll paid to route around
    // it never enters query_dist, so leaving it in would inflate ref_dist without inflating
    // query_dist -- handing the group's other variants free credit for a variant the query missed.
    auto emit_sync_group = [&](int q_ref_pos, int t_pos) {
        int ref_dist = 0;
        wf_ed(splice_out(graph->ref, q_ref_pos, prev_query_ref_pos, excised_ref),
                splice_out(graph->truth, t_pos, prev_truth_pos, excised_truth), ref_dist);
        if (print) printf("syncing\n");
        float credit = 0;
        if (ref_dist == 0) {
            // false positive with no nearby truth variant, credit = 0
        } else {
            credit = 1 - float(query_dist) / ref_dist;
        }
        errtype_t errtype = (credit >= g.credit_threshold) ? ERRTYPE_TP : ERRTYPE_FP;
        float qual = g.max_qual;
        for (int qvar_idx : sync_qvars) {
            qual = std::min(qual, qvars->var_quals[qvar_idx]);
        }
        for (int qvar_idx : sync_qvars) {
            if (print) printf("QUERY var %d: BD=%s, BC=%f, Q=%f, SG=%d, RD=%d, QD=%d\n",
                    qvar_idx, error_strs[errtype].data(), credit,
                    qual, sync_group, ref_dist, query_dist);
            qvars->errtypes[truth_hap][qvar_idx] = errtype;
            qvars->callq[truth_hap][qvar_idx] = qual;
            qvars->sync_group[truth_hap][qvar_idx] = sync_group;
            qvars->ref_ed[truth_hap][qvar_idx] = ref_dist;
            qvars->query_ed[truth_hap][qvar_idx] = query_dist;
            qvars->credit[truth_hap][qvar_idx] = credit;
            if (errtype == ERRTYPE_TP)
                qvars->set_var_calcgt_on_hap(qvar_idx, truth_hap, true);
        }
        if (errtype == ERRTYPE_FP) errtype = ERRTYPE_FN;
        for (int tvar_idx : sync_tvars) {
            if (print) printf("TRUTH var %d: BD=%s, BC=%f, Q=%f, SG=%d, RD=%d, QD=%d\n",
                    tvar_idx, error_strs[errtype].data(), credit,
                    qual, sync_group, ref_dist, query_dist);
            tvars->errtypes[truth_hap][tvar_idx] = errtype;
            tvars->callq[truth_hap][tvar_idx] = qual;
            tvars->sync_group[truth_hap][tvar_idx] = sync_group;
            tvars->ref_ed[truth_hap][tvar_idx] = ref_dist;
            tvars->query_ed[truth_hap][tvar_idx] = query_dist;
            tvars->credit[truth_hap][tvar_idx] = credit;

            // Mirror of the query side above: record the matched query calls on the truth variant,
            // so its ac_errtype can report the query's allele count. The sync group is the atomic
            // matching unit, so the count is the union over the calls it holds -- two oppositely
            // phased heterozygous calls therefore recover both haplotypes, not one.
            //
            // A 1|1 truth variant is emitted in both truth-haplotype passes, so a haplotype the
            // first pass recovered is skipped rather than re-set, which would be an error.
            if (errtype == ERRTYPE_TP) {
                for (int qvar_idx : sync_qvars) {
                    for (int hap = 0; hap < HAPS; hap++) {
                        if (qvars->var_on_hap(qvar_idx, hap) &&
                                !tvars->var_on_hap(tvar_idx, hap, /*calc=*/ true))
                            tvars->set_var_calcgt_on_hap(tvar_idx, hap, true);
                    }
                }
            }
        }
        sync_group++;
        sync_qvars.clear();
        sync_tvars.clear();
        excised_ref.clear();
        excised_truth.clear();
        prev_query_ref_pos = q_ref_pos;
        prev_truth_pos = t_pos;
        query_dist = 0;
    };

    // Record a bypassed variant's span for excision from the enclosing group, without splitting
    // that group. The variant node is always emitted immediately before its bypass node (see Graph
    // constructor), so get_truth_pos on that variant node (never on the bypass node itself) yields
    // the truth offset of the off-path alt.
    auto excise_bypass = [&](int bypass_tni) {
        int var_tni = bypass_tni - 1;
        assert(graph->tidxs[var_tni] == graph->tskips[bypass_tni]);
        int truth_beg = graph->get_truth_pos(var_tni, 0);
        int alt_len = int(graph->tseqs[var_tni].size()) - 1; // each tseq starts with '_'
        excised_ref.push_back({graph->tbegs[bypass_tni], graph->tends[bypass_tni]});
        excised_truth.push_back({truth_beg, truth_beg + alt_len});
    };

    while (curr != idx4(0, 0, -1, -1)) {

        idx4 prev = ptrs.at(curr);
        bool curr_bypass = graph->tskips[curr.tni] >= 0;
        bool prev_bypass = graph->tskips[prev.tni] >= 0;

        if (print) printf("curr = node (%d, %d) cell (%d, %d) poss (%d, %d)",
                curr.qni, curr.tni, curr.qi, curr.ti, 
                graph->qbegs[curr.qni]+curr.qi, graph->tbegs[curr.tni]+curr.ti);
        if (print) printf("\tprev = node (%d, %d) cell (%d, %d)\n",
                prev.qni, prev.tni, prev.qi, prev.ti);

        /* printf("%s submatrix, %s diag, query %s, truth %s, %s pos\n", */
        /*     (prev.qni == curr.qni && prev.tni == curr.tni) ? "same" : "diff", */
        /*     (prev.qi+1 == curr.qi && prev.ti+1 == curr.ti) ? "is" : "is not", */
        /*     (graph->qtypes[curr.qni] == TYPE_REF) ? "ref" : "var", */
        /*     (graph->ttypes[curr.tni] == TYPE_REF) ? "ref" : "var", */
        /*     (graph->tbegs[curr.tni] + curr.ti == graph->qbegs[curr.qni] + curr.qi) ? "same" : "diff"); */

        // if we move out of a new query variant, mark it as included
        if (prev.qni != curr.qni && // new query node
                graph->qtypes[curr.qni] != TYPE_REF) { // node is variant
            int qvar_idx = graph->qidxs[curr.qni];
            sync_qvars.push_back(qvar_idx);
            if (print) printf("new query variant: %d\n", qvar_idx);
        }
        // if we move out of a query variant, include it in sync group and ref dist calc
        if (prev.tni != curr.tni && // new truth node
                graph->ttypes[curr.tni] != TYPE_REF) { // node is variant
            int tvar_idx = graph->tidxs[curr.tni];
            sync_tvars.push_back(tvar_idx);
            if (print) printf("new truth variant: %d\n", tvar_idx);
        }
        // if we move into a bypass node, the skipped truth variant is a false negative, and its
        // span is excised from the enclosing group's credit measurement. This fires once per bypass
        // node, so consecutive bypassed truth variants are each excised (not just the first one).
        if (prev.tni != curr.tni && curr_bypass) {
            int tvar_idx = graph->tskips[curr.tni];
            tvars->errtypes[truth_hap][tvar_idx] = ERRTYPE_FN;
            tvars->credit[truth_hap][tvar_idx] = 0;
            tvars->ref_ed[truth_hap][tvar_idx] = 0;
            tvars->query_ed[truth_hap][tvar_idx] = 0;
            tvars->sync_group[truth_hap][tvar_idx] = sync_group;
            excise_bypass(curr.tni);
            if (print) printf("bypassed (FN) truth variant: %d\n", tvar_idx);
        }
        // if the alignment is a substitution, insertion, or deletion. Edits taken inside a bypass
        // node are against the bypassed reference allele, which is excised from the group's
        // ref_dist, so charging them to query_dist would penalize a span not being measured.
        if (prev.qni == curr.qni && prev.tni == curr.tni && // same matrix
                !curr_bypass &&
                (prev.qi == curr.qi || prev.ti == curr.ti || // insertion or deletion
                 graph->tseqs[curr.tni][curr.ti] != graph->qseqs[curr.qni][curr.qi]) // substitution
                ) {
            if (print) printf("non-match step\n");
            query_dist += 1;
        }

        // check if this movement is a sync point (ref main diag mvmt or between var main diag mvmt)
        int truth_ref_pos = graph->tbegs[curr.tni] + curr.ti;
        int query_ref_pos = graph->qbegs[curr.qni] + curr.qi;
        bool on_main_diag = (truth_ref_pos == query_ref_pos);
        bool same_submatrix = curr.qni == prev.qni && curr.tni == prev.tni;
        bool diff_submatrix = curr.qni != prev.qni && curr.tni != prev.tni; // both must differ
        bool ref_query_move = graph->qtypes[curr.qni] == TYPE_REF 
            && prev.qni == curr.qni
            && prev.qi < curr.qi;
        bool ref_truth_move = graph->ttypes[curr.tni] == TYPE_REF 
            && prev.tni == curr.tni
            && prev.ti < curr.ti;
        bool sync_point = on_main_diag && (
                (same_submatrix && ref_query_move && ref_truth_move) || diff_submatrix);

        // A bypassed variant is an off-path false negative; its span is excised (in the FN block
        // above) from the enclosing group's credit measurement rather than splitting the group in
        // two. These boundaries only bracket the query variants that aligned inside the bypass
        // region so they can be dropped from the group. No get_truth_pos/wf_ed may be taken with
        // curr inside a bypass node (get_truth_pos would overshoot this->truth), so sync points are
        // still suppressed there. A run of consecutive bypass nodes is bracketed by a single
        // entry (its top) and a single exit (its bottom).
        if (prev.tni != curr.tni && prev_bypass && !curr_bypass) {
            // ENTRY (backtrack about to descend from the real node above into the bypass below):
            // remember how many query variants the enclosing group held, so calls aligned inside
            // the bypass can be dropped on exit.
            if (print) printf("bypass entry boundary\n");
            qvars_before_bypass = sync_qvars.size();
        } else if (prev.tni != curr.tni && curr_bypass && !prev_bypass) {
            // EXIT (backtrack leaving the bottom of the bypass into the real node below): query
            // variants aligned inside the bypass lie in the excised span, so they are dropped from
            // the group and keep their default FP.
            if (print) printf("bypass exit boundary\n");
            if (sync_qvars.size() > qvars_before_bypass)
                sync_qvars.resize(qvars_before_bypass);
        } else if (sync_point && !curr_bypass) {
            if (print) printf("potential sync point\n");
            // add sync point
            if (sync_tvars.size() || sync_qvars.size())
                emit_sync_group(query_ref_pos, graph->get_truth_pos(curr.tni, curr.ti));
        }
        curr = prev;
    }
}

/**************************************************************************************************/

/**
 * @brief Computes Smith-Waterman gap-affine alignment score between two sequences.
 *
 * Uses the wavefront algorithm with three matrices (substitution, insertion, deletion)
 * to compute the minimum gap-affine alignment cost between query and truth.
 *
 * @param[in] query The query sequence to align.
 * @param[in] truth The truth sequence to align against.
 * @param[out] s Output variable set to the alignment score.
 * @param[in] x Substitution penalty.
 * @param[in] o Gap-open penalty.
 * @param[in] e Gap-extension penalty.
 * @param[in] print Whether to enable debug printing.
 */
void wf_swg_align(
        const std::string & query, const std::string & truth,
        int & s, int x, int o, int e, bool print
        ) {

    // init
    int query_len = query.size();
    int truth_len = truth.size();

    // early exit if either string is empty
    if (!query_len && !truth_len) { s = 0; return; }
    if (!query_len) { s = o + e*truth_len; return; }
    if (!truth_len) { s = o + e*query_len; return; }

    int mat_len = query_len + truth_len - 1;
    bool done = false;
    EnumArray<mat_t, std::vector< std::vector<int> >, MAT_SLOTS> offs{};
    for (mat_t m : EnumRange<mat_t, MAT_SLOTS>{}) {
        offs[m].push_back(std::vector<int>(mat_len, -2));
    }
    s = 0;
    offs[MAT_SUB][s][query_len-1] = -1; // main diag

    while (true) {

        // EXTEND WAVEFRONT (leave INS, DEL)
        for (mat_t m : {MAT_INS, MAT_DEL}) {
            for (int d = 0; d < mat_len; d++) {
                int off = offs[m][s][d];
                int diag = d + 1 - query_len;

                if (off >= 0 && off < query_len &&
                        diag+off >= 0 && diag+off < truth_len &&
                        offs[m][s][d] >= offs[MAT_SUB][s][d]) {
                    offs[MAT_SUB][s][d] = offs[m][s][d];
                    if(print) printf("(S, %d, %d) swap\n", offs[MAT_SUB][s][d], 
                            offs[MAT_SUB][s][d]+d+1-query_len);
                }
            }
        }

        // EXTEND WAVEFRONT (diag, SUB only)
        for (int d = 0; d < mat_len; d++) {
            int off = offs[MAT_SUB][s][d];
            int diag = d + 1 - query_len;

            // extend
            while ( off != -2 && diag + off >= -1 && 
                    off < query_len - 1 && 
                    diag + off < truth_len - 1) {
                if (query[off+1] == truth[diag+off+1]) off++;
                else break;
            }
            if (off > offs[MAT_SUB][s][d])
                if(print) printf("(S, %d, %d) extend\n", off, off+diag);
            offs[MAT_SUB][s][d] = off;

            // finish if done
            if (off == query_len - 1 && off + diag == truth_len - 1)
            { done = true; break; }
        }
        if (done) break;

        // debug print
        for (mat_t mi : EnumRange<mat_t, MAT_SLOTS>{}) {
            if(print) printf("\n%s matrix\n", type_strs[mat_to_edittype(mi)].data());
            if(print) printf("offs %d:", s);
            for (int di = 0; di < int(query.size() + truth.size()-1); di++) {
                if(print) printf("\t%d", offs[mi][s][di]);
            }
            if(print) printf("\n");
        }

        // NEXT WAVEFRONT
        s++;
        if(print) printf("\nscore = %d\n", s);
        for (mat_t m : EnumRange<mat_t, MAT_SLOTS>{}) {
            offs[m].push_back(std::vector<int>(mat_len, -2));
        }

        for (int d = 0; d < mat_len; d++) {
            int diag = d + 1 - query_len;

            // sub (in SUB)
            if (s-x >= 0 && offs[MAT_SUB][s-x][d] != -2 && 
                            offs[MAT_SUB][s-x][d]+1 < query_len &&
                     diag + offs[MAT_SUB][s-x][d]+1 < truth_len &&
                            offs[MAT_SUB][s-x][d]+1 >= offs[MAT_SUB][s][d]) {
                offs[MAT_SUB][s][d] = offs[MAT_SUB][s-x][d] + 1;
                if(print) printf("(S, %d, %d) sub\n", offs[MAT_SUB][s][d], 
                        offs[MAT_SUB][s][d]+diag);
            }

            // open gap (enter DEL)
            if (s-(o+e) >= 0 && d > 0 && 
                           offs[MAT_SUB][s-(o+e)][d-1] != -2 &&
                    diag + offs[MAT_SUB][s-(o+e)][d-1] < truth_len &&
                           offs[MAT_SUB][s-(o+e)][d-1] >= offs[MAT_DEL][s][d]) {
                offs[MAT_DEL][s][d] = offs[MAT_SUB][s-(o+e)][d-1];
                if(print) printf("(D, %d, %d) open\n", offs[MAT_DEL][s][d], 
                        offs[MAT_DEL][s][d]+diag);
            }

            // open gap (enter INS)
            if (s-(o+e) >= 0 && d < mat_len-1 && 
                           offs[MAT_SUB][s-(o+e)][d+1] != -2 &&
                           offs[MAT_SUB][s-(o+e)][d+1]+1 < query_len &&
                    diag + offs[MAT_SUB][s-(o+e)][d+1]+1 < truth_len &&
                    diag + offs[MAT_SUB][s-(o+e)][d+1]+1 >= 0 &&
                           offs[MAT_SUB][s-(o+e)][d+1]+1 >= offs[MAT_INS][s][d]) {
                offs[MAT_INS][s][d] = offs[MAT_SUB][s-(o+e)][d+1]+1;
                if(print) printf("(I, %d, %d) open\n", offs[MAT_INS][s][d], 
                        offs[MAT_INS][s][d]+diag);
            }

            // extend gap (stay DEL)
            if (s-e >= 0 && d > 0 && 
                           offs[MAT_DEL][s-e][d-1] != -2 &&
                    diag + offs[MAT_DEL][s-e][d-1] < truth_len &&
                           offs[MAT_DEL][s-e][d-1] >= offs[MAT_DEL][s][d]) {
                offs[MAT_DEL][s][d] = offs[MAT_DEL][s-e][d-1];
                if(print) printf("(D, %d, %d) extend\n", offs[MAT_DEL][s][d], 
                        offs[MAT_DEL][s][d]+diag);
            }

            // extend gap (stay INS)
            if (s-e >= 0 && d < mat_len-1 && 
                           offs[MAT_INS][s-e][d+1] != -2 &&
                           offs[MAT_INS][s-e][d+1]+1 < query_len &&
                    diag + offs[MAT_INS][s-e][d+1]+1 < truth_len &&
                    diag + offs[MAT_INS][s-e][d+1]+1 >= 0 &&
                           offs[MAT_INS][s-e][d+1]+1 >= offs[MAT_INS][s][d]) {
                offs[MAT_INS][s][d] = offs[MAT_INS][s-e][d+1]+1;
                if(print) printf("(I, %d, %d) extend\n", offs[MAT_INS][s][d], 
                        offs[MAT_INS][s][d]+diag);
            }
        }
    }
}

/**************************************************************************************************/

/**
 * @brief Launches threaded precision/recall evaluation across all superclusters.
 *
 * Distributes superclusters across threads according to their predicted RAM usage,
 * using the sorted size groups from sort_superclusters().
 *
 * @param[in] clusterdata_ptr Pointer to supercluster data containing all variants.
 * @param[in] sc_groups Size-grouped supercluster indices from sort_superclusters().
 */
void precision_recall_threads_wrapper(
        std::shared_ptr<superclusterData> clusterdata_ptr,
        std::vector< EnumArray<idxdim_t, std::vector<int>, IDXDIM_SLOTS> > sc_groups) {

    if (g.verbosity >= 1 ) 
    for (int i = 0; i < g.thread_nsteps; i++) {
        INFO("  Superclusters using %7.3f to %7.3f GB RAM each (%3d threads): %8d",
                i == 0 ? 0 : g.ram_steps[i-1], g.ram_steps[i], g.thread_steps[i],
                int(sc_groups[i][CTG_IDX].size()));
    }

    int thread_step = g.thread_nsteps-1;
    int start = 0;
    while (thread_step >= 0) {

        // init
        int nthreads = g.thread_steps[thread_step];
        int nscs = sc_groups[thread_step][SC_IDX].size() - start;
        std::vector<std::thread> threads;

        // all threads can solve at least one problem at this level
        if (nscs >= nthreads) {

            // distribute many subproblems evenly among threads
            bool thread2 = thread_step != 0; // max_threads/2+
            for (int t = 0; t < nthreads; t++) {
                int size = nscs / nthreads;
                threads.push_back(std::thread(precision_recall_wrapper,
                            clusterdata_ptr.get(), std::cref(sc_groups),
                            thread_step, start, start+size, thread2, /* print = */ false));
                start += size;
            }
            for (std::thread & t : threads)
                t.join();

            // we fully finished all problems at this size
            if (nscs % nthreads == 0) {
                thread_step--;
                start = 0;
            }

        } else { // not enough work for all threads at this level

            // each thread solves one problem, 
            // at multiple levels until RAM limit reached
            float total_ram = 0;
            while (total_ram < g.max_ram && thread_step >= 0) {
                while (sc_groups[thread_step][SC_IDX].size() == 0) {
                    thread_step--;
                    if (thread_step < 0) break;
                }
                bool thread2 = thread_step != 0; // max_threads/2+
                if (thread_step < 0) break;
                threads.push_back(std::thread(precision_recall_wrapper,
                            clusterdata_ptr.get(), std::cref(sc_groups),
                            thread_step, start, start+1, thread2, /* print = */ false));
                start++;
                total_ram += g.ram_steps[thread_step];
                if (start >= int(sc_groups[thread_step][SC_IDX].size())) {
                    start = 0;
                    thread_step--;
                }
            }

            for (std::thread & t : threads)
                t.join();
        }
    }
}

/**************************************************************************************************/

/**
 * @brief Prints graph node sequences and connectivity to console for debugging.
 */
void Graph::print() {
    printf("QUERY:\n");
    for (int qn = 0; qn < this->qnodes; qn++) {
        printf("node %d = %s %s\n", qn, this->qseqs[qn].data(), type_strs[this->qtypes[qn]].data());
        printf("\tprev nodes: ");
        for (int n2 : this->qprevs[qn]) printf("%d, ", n2);
        printf("\n");
        printf("\tnext nodes: ");
        for (int n2 : this->qnexts[qn]) printf("%d, ", n2);
        printf("\n");
    }
    printf("\nTRUTH:\n");
    for (int tn = 0; tn < this->tnodes; tn++) {
        printf("node %d = %s %s\n", tn, this->tseqs[tn].data(), type_strs[this->ttypes[tn]].data());
        printf("\tprev nodes: ");
        for (int n2 : this->tprevs[tn]) printf("%d, ", n2);
        printf("\n");
        printf("\tnext nodes: ");
        for (int n2 : this->tnexts[tn]) printf("%d, ", n2);
        printf("\n");
    }
}

/**************************************************************************************************/

/**
 * @brief Maps a truth graph node and variant index to its 0-based position in the truth sequence.
 *
 * Reference-allele bypass nodes (tskips[tn] >= 0) are skipped in the summation because they
 * are alternative paths, not part of the concatenated this->truth haplotype string.
 *
 * @param[in] truth_node_idx Truth node index in graph.
 * @param[in] truth_idx Position index within the truth node sequence.
 * @return 0-based position in the combined truth sequence.
 */
int Graph::get_truth_pos(int truth_node_idx, int truth_idx) {
    int truth_pos = 0;
    for (int tn = 0; tn < truth_node_idx; tn++) {
        if (this->tskips[tn] >= 0) continue; // bypass nodes are not part of this->truth
        truth_pos += this->tseqs[tn].size() - 1; // each tseq starts with '_'
    }
    truth_pos += truth_idx;
    return truth_pos;
}

/**************************************************************************************************/

/**
 * @brief Constructs alignment graph from supercluster variants and reference sequence.
 *
 * Builds a DAG where query nodes represent all variant and reference paths, and truth
 * nodes represent the selected truth haplotype path as a truth DAG: each truth variant node
 * is paired with a parallel reference-allele bypass node (tskips[tni] set to the bypassed
 * variant's index) offering an alternate, tolled route past that variant, with reference end
 * coordinates (tends) recorded for every truth node and connectivity set between adjacent nodes.
 *
 * Node 0 of each side is always a reference node, which is what lets calc_prec_recall_aln() seed
 * its search at a fixed origin cell. Away from the contig start that node is the one-base left
 * flank; at reference position 0, where no base lies to the left, a synthetic zero-width reference
 * node stands in for it so that a variant's parallel allele still has a predecessor.
 *
 * Every node's coordinate span equals the length of the sequence it holds, with zero-width insertion
 * variant and bypass nodes the deliberate exception. The reference window is clamped at the contig
 * end to keep that true of the trailing node, which is otherwise the one place where the coordinate
 * and the sequence could disagree; at a contig end it becomes a zero-width sink.
 *
 * @param[in] sc Supercluster data containing query and truth variant containers.
 * @param[in] sc_idx Supercluster index in the contig.
 * @param[in] ref Reference FASTA data.
 * @param[in] ctg Contig name.
 * @param[in] truth_hap Truth haplotype index (0 or 1).
 * @throws ERROR if a reference contig is not found in the FASTA.
 */
Graph::Graph(
		std::shared_ptr<ctgSuperclusters> sc, int sc_idx,
        std::shared_ptr<fastaData> ref, const std::string & ctg, hap_t truth_hap) {

    ////////////////////////////////
    // STEP 1: CREATE QUERY NODES //
    ////////////////////////////////

    // initialize helper variables
    std::shared_ptr<ctgVariants> qvars = sc->callset_vars[QUERY];
    std::shared_ptr<ctgVariants> tvars = sc->callset_vars[TRUTH];
    int qvar_beg = std::distance(qvars->superclusters.begin(),
            std::lower_bound(qvars->superclusters.begin(), qvars->superclusters.end(), sc_idx));
    int qvar_end = std::distance(qvars->superclusters.begin(),
            std::upper_bound(qvars->superclusters.begin(), qvars->superclusters.end(), sc_idx));
    int tvar_beg = std::distance(tvars->superclusters.begin(),
            std::lower_bound(tvars->superclusters.begin(), tvars->superclusters.end(), sc_idx));
    int tvar_end = std::distance(tvars->superclusters.begin(),
            std::upper_bound(tvars->superclusters.begin(), tvars->superclusters.end(), sc_idx));
    int ref_beg = sc->get_min_ref_pos(qvar_beg, qvar_end, tvar_beg, tvar_end);
    int ref_end = sc->get_max_ref_pos(qvar_beg, qvar_end, tvar_beg, tvar_end);
    // exclusive end of the reference window every node draws its sequence from. It reaches one past
    // ref_end, giving the window a right flank as ref_beg = min_pos - 1 gives it a left one, and is
    // clamped at the contig end so that a node's coordinate span never exceeds the sequence
    // substr() hands it -- the mirror of ref_beg clamping at position 0 (#189)
    const int win_end = std::min(ref_end + 1, int(ref->fasta.at(ctg).size()));

    int ref_pos = ref_beg;
    this->sc = sc;
    this->sc_idx = sc_idx;
    // keep track of all node ends. variants are already sorted in order of their starts, but
    // to create the correct reference substrings we need to know where the next end is too
    std::priority_queue<int, std::vector<int>, std::greater<int> > qnode_ends;

    // iterate through all the variants
    this->qnodes = 0;
    for (int var_idx = qvar_beg; var_idx < qvar_end; var_idx++) {
        // skip variants that we've already evaluated
        if (qvars->errtypes[truth_hap][var_idx] != ERRTYPE_UN) { continue; }
        
        // prior to adding the next variant, add as many reference nodes as necessary
        // due to earlier variants that end before it starts
        int var_pos = qvars->poss[var_idx];
        while (ref_pos < var_pos) {
            // get length of this reference segment
            int next_ref_pos; 
            if (!qnode_ends.empty() && qnode_ends.top() < var_pos) { // prev var ends before next starts
                next_ref_pos = qnode_ends.top();
                // multiple vars may end at same location; remove all from node_ends
                while (!qnode_ends.empty() && qnode_ends.top() == next_ref_pos) qnode_ends.pop();
            } else {
                next_ref_pos = var_pos;
            }
            // add reference node
            assert(next_ref_pos <= var_pos);
            this->qnodes++;
            this->qseqs.push_back("_" + ref->fasta.at(ctg).substr(ref_pos, next_ref_pos-ref_pos));
            this->qbegs.push_back(ref_pos - ref_beg);
            this->qends.push_back(next_ref_pos - ref_beg);
            this->qtypes.push_back(TYPE_REF);
            this->qidxs.push_back(-1);
            ref_pos = next_ref_pos;
        }

        // At position 0 there is no base to the left, so the one-base left flank node that would
        // otherwise open the graph cannot exist and this variant node would become node 0 -- the
        // hardcoded origin of calc_prec_recall_aln(), leaving its parallel reference allele with no
        // predecessor and unreachable. A zero-width reference node supplies the origin cell the
        // aligner needs; its sentinel is all the flank node ever contributed there (#177). No
        // position test is needed: ref_beg = max(0, min_pos - 1), so a side reaches its first
        // variant with nothing emitted only when ref_pos == var_pos == ref_beg == 0.
        if (this->qnodes == 0) {
            this->qnodes++;
            this->qseqs.push_back("_");
            this->qbegs.push_back(0);
            this->qends.push_back(0);
            this->qtypes.push_back(TYPE_REF);
            this->qidxs.push_back(-1);
        }

        // add the variant
        assert(ref_pos == var_pos);
        this->qnodes++;
        this->qseqs.push_back("_" + qvars->alts[var_idx]);
        this->qbegs.push_back(qvars->poss[var_idx] - ref_beg);
        this->qends.push_back(qvars->poss[var_idx] + qvars->rlens[var_idx] - ref_beg);
        this->qtypes.push_back(qvars->types[var_idx]);
        this->qidxs.push_back(var_idx);
        if (qvars->rlens[var_idx]) 
            qnode_ends.push(qvars->poss[var_idx] + qvars->rlens[var_idx]);
    }

    // all variants added, add the remainder of the reference
    while (ref_pos < ref_end) {
        // get the length of this reference segment
        int next_ref_pos;
        bool last_segment = false;
        if (!qnode_ends.empty() && qnode_ends.top() < ref_end) { // stop at variant end
            next_ref_pos = qnode_ends.top();
            // multiple vars may end at same location; remove all from node_ends
            while (!qnode_ends.empty() && qnode_ends.top() == next_ref_pos) qnode_ends.pop();
        } else {
            next_ref_pos = win_end; // add remainder of reference in this supercluster
            // at a contig end win_end can equal ref_pos, leaving this trailing node zero-width and
            // the loop condition still true, so close the loop here rather than on ref_pos
            last_segment = true;
        }
        this->qnodes++;
        this->qseqs.push_back("_" + ref->fasta.at(ctg).substr(ref_pos, next_ref_pos-ref_pos));
        this->qbegs.push_back(ref_pos - ref_beg);
        this->qends.push_back(next_ref_pos - ref_beg);
        this->qtypes.push_back(TYPE_REF);
        this->qidxs.push_back(-1);
        ref_pos = next_ref_pos;
        if (last_segment) break;
    }

    /////////////////////////////////////
    // STEP 2: SET QUERY NODE POINTERS //
    /////////////////////////////////////
    this->qprevs.resize(this->qnodes);
    this->qnexts.resize(this->qnodes);

    for (int n1 = 0; n1 < this->qnodes; n1++) {
        for (int n2 = 0; n2 < this->qnodes; n2++) {
            if (n2 == n1) continue; // don't compare node to itself
            // add predecessor of current node
            if (this->qbegs[n1] == this->qends[n2] && n2 < n1)
                this->qprevs[n1].push_back(n2);
            // add successor of current node
            if (this->qends[n1] == this->qbegs[n2] && n1 < n2)
                this->qnexts[n1].push_back(n2);
        }
    }

    ////////////////////////////////
    // STEP 3: CREATE TRUTH NODES //
    ////////////////////////////////

    // iterate through all the variants
    ref_pos = ref_beg;
    this->tnodes = 0;
    this->truth = "";
    for (int var_idx = tvar_beg; var_idx < tvar_end; var_idx++) {
        // skip variants that we've already evaluated
        if (tvars->errtypes[truth_hap][var_idx] != ERRTYPE_UN) { continue; }

        if (tvars->var_on_hap(var_idx, truth_hap)) { // ignore variant if on other hap
            // add reference node before next truth variant
            int var_pos = tvars->poss[var_idx];
            if (var_pos > ref_pos) {
                this->tnodes++;
                this->tseqs.push_back("_" + ref->fasta.at(ctg).substr(ref_pos, var_pos-ref_pos));
                this->tbegs.push_back(ref_pos - ref_beg);
                this->tends.push_back(var_pos - ref_beg);
                this->ttypes.push_back(TYPE_REF);
                this->tidxs.push_back(-1);
                this->tskips.push_back(-1);
                this->truth += ref->fasta.at(ctg).substr(ref_pos, var_pos-ref_pos);
            }

            // no left flank can exist at position 0, so keep node 0 a reference node for the
            // aligner's origin; see the query-side counterpart in STEP 1 (#177)
            if (this->tnodes == 0) {
                this->tnodes++;
                this->tseqs.push_back("_");
                this->tbegs.push_back(0);
                this->tends.push_back(0);
                this->ttypes.push_back(TYPE_REF);
                this->tidxs.push_back(-1);
                this->tskips.push_back(-1);
            }

            // add the truth variant
            this->tnodes++;
            this->tseqs.push_back("_" + tvars->alts[var_idx]);
            int tvar_rlen = tvars->rlens[var_idx];
            this->tbegs.push_back(var_pos - ref_beg);
            this->tends.push_back(var_pos + tvar_rlen - ref_beg);
            this->ttypes.push_back(tvars->types[var_idx]);
            this->tidxs.push_back(var_idx);
            this->tskips.push_back(-1);
            this->truth += tvars->alts[var_idx];

            // parallel reference-allele bypass node (declares this truth variant FN if taken)
            this->tnodes++;
            this->tseqs.push_back("_" + ref->fasta.at(ctg).substr(var_pos, tvar_rlen));
            this->tbegs.push_back(var_pos - ref_beg);
            this->tends.push_back(var_pos + tvar_rlen - ref_beg);
            this->ttypes.push_back(TYPE_REF);
            this->tidxs.push_back(-1);
            this->tskips.push_back(var_idx);

            ref_pos = tvars->poss[var_idx] + tvars->rlens[var_idx];
        }
    }

    // add the remainder of the truth. At a contig end win_end can equal ref_pos, leaving this a
    // zero-width sink node; it stays the node both alleles converge on, and the insertion-leap rule
    // below cannot mistake it for an insertion because it is neither a variant nor a bypass node
    this->tnodes++;
    this->tseqs.push_back("_" + ref->fasta.at(ctg).substr(ref_pos, win_end - ref_pos));
    this->tbegs.push_back(ref_pos - ref_beg);
    this->tends.push_back(win_end - ref_beg);
    this->ttypes.push_back(TYPE_REF);
    this->tidxs.push_back(-1);
    this->tskips.push_back(-1);
    this->truth += ref->fasta.at(ctg).substr(ref_pos, win_end - ref_pos);

    /////////////////////////////////////
    // STEP 4: SET TRUTH NODE POINTERS //
    /////////////////////////////////////

    this->tprevs.resize(this->tnodes);
    this->tnexts.resize(this->tnodes);

    // coordinates hosting a zero-width truth insertion variant node; a direct ref->ref edge
    // across such a locus would give a free (cost-0) path skipping both the alt (variant) and
    // the tolled bypass node, circumventing the bypass toll and mislabeling matched insertions FN
    std::unordered_set<int> insertion_coords;
    for (int tn = 0; tn < this->tnodes; tn++)
        if (this->tidxs[tn] >= 0 && this->tbegs[tn] == this->tends[tn])
            insertion_coords.insert(this->tbegs[tn]);

    for (int n1 = 0; n1 < this->tnodes; n1++) {
        for (int n2 = 0; n2 < this->tnodes; n2++) {
            if (n2 == n1) continue;
            // a variant node and its own bypass node are parallel alternatives, never
            // sequential; skip wiring them together (matters for zero-width insertions,
            // where variant and bypass share tbegs == tends)
            if (this->tskips[n2] >= 0 && this->tskips[n2] == this->tidxs[n1]) continue;
            if (this->tskips[n1] >= 0 && this->tskips[n1] == this->tidxs[n2]) continue;
            // suppress any edge that leaps a zero-width insertion locus, forcing the path through
            // the insertion's variant node (TP) or its tolled bypass node (FN). An edge joining two
            // nodes at coordinate p leaps the insertion unless one endpoint IS the insertion's own
            // alt/bypass node, in which case the edge routes into or out of the insertion rather
            // than past it. Such an endpoint is exactly a zero-width variant or bypass node; testing
            // for that (rather than the old both-ref rule) also closes the leap when the insertion
            // abuts another variant, whose alt/bypass node is reference-spanning but not a plain ref
            // node, and keeps a zero-width node that is neither (the contig-start entry node of
            // STEP 1/STEP 3) from exempting an edge that really does leap the insertion.
            bool n1_ins_node = this->tbegs[n1] == this->tends[n1] &&
                    (this->tidxs[n1] >= 0 || this->tskips[n1] >= 0);
            bool n2_ins_node = this->tbegs[n2] == this->tends[n2] &&
                    (this->tidxs[n2] >= 0 || this->tskips[n2] >= 0);
            bool leaps_insertion = !n1_ins_node && !n2_ins_node;
            if (this->tbegs[n1] == this->tends[n2] && n2 < n1 &&
                    !(leaps_insertion && insertion_coords.count(this->tbegs[n1])))
                this->tprevs[n1].push_back(n2);
            if (this->tends[n1] == this->tbegs[n2] && n1 < n2 &&
                    !(leaps_insertion && insertion_coords.count(this->tends[n1])))
                this->tnexts[n1].push_back(n2);
        }
    }

    this->ref = ref->fasta.at(ctg).substr(ref_beg, win_end - ref_beg);
}

/**************************************************************************************************/

/**
 * @brief Evaluates a subset of superclusters within a single thread.
 *
 * Iterates over the range [start, stop) of superclusters in the given size group
 * and calls evaluate_variants() for each haplotype combination.
 *
 * @param[in] clusterdata_ptr Raw pointer to supercluster data.
 * @param[in] sc_groups Size-grouped supercluster indices.
 * @param[in] thread_step Index into the thread RAM step buckets.
 * @param[in] start Inclusive start index within the sc_groups[thread_step] list.
 * @param[in] stop Exclusive stop index within the sc_groups[thread_step] list.
 * @param[in] thread2 True when running at max_threads/2 or more.
 * @param[in] print Whether to enable debug printing.
 */
void precision_recall_wrapper(
        superclusterData* clusterdata_ptr,
        const std::vector< EnumArray<idxdim_t, std::vector<int>, IDXDIM_SLOTS> > & sc_groups,
        int thread_step, int start, int stop, bool thread2, bool print) {

	// parse sc_idx from grouped superclusters
    if (stop == start) return;
    for (int supclust_idx = start; supclust_idx < stop; supclust_idx++) {
        std::string ctg = clusterdata_ptr->contigs[
            sc_groups[thread_step][CTG_IDX][supclust_idx]];
        int sc_idx = sc_groups[thread_step][SC_IDX][supclust_idx];

        // set superclusters pointer
        std::shared_ptr<ctgSuperclusters> scs = clusterdata_ptr->superclusters[ctg];

        if (print) {
            // print cluster info
            printf("\n\nSupercluster: %d\n", sc_idx);
            for (callset_t c : EnumRange<callset_t, CALLSET_SLOTS>{}) {
                std::shared_ptr<ctgVariants> vars = scs->callset_vars[c];
                int var_beg = std::distance(vars->superclusters.begin(),
                        std::lower_bound(vars->superclusters.begin(), 
                                         vars->superclusters.end(), sc_idx));
                int var_end = std::distance(vars->superclusters.begin(),
                        std::upper_bound(vars->superclusters.begin(), 
                                         vars->superclusters.end(), sc_idx));
                printf("%s: %d variants (%d-%d)\n", callset_strs[c].data(),
                        var_end-var_beg, var_beg, var_end);
                for (int var_idx = var_beg; var_idx < var_end; var_idx++) {
                    printf("\t\t%s %d\t%s\t%s\t%s\tQ=%f\n", ctg.data(), vars->poss[var_idx], 
                    vars->refs[var_idx].size() ?  vars->refs[var_idx].data() : "_", 
                    vars->alts[var_idx].size() ?  vars->alts[var_idx].data() : "_",
                    gt_strs[vars->orig_gts[var_idx]].data(),
                    vars->var_quals[var_idx]);
                }
            }
        }
        
        // calculate two forward-pass alignments, saving path
        // query1/query2 graph to truth1, query1/query2 graph to truth2
        for (hap_t hi : EnumRange<hap_t, HAP_SLOTS>{}) {
            if (print) printf("HAP %d\n", int(idx(hi)));
            evaluate_variants(scs, sc_idx, clusterdata_ptr->ref, ctg, hi, print);
        }
    }
}

/**************************************************************************************************/

/**
 * @brief Extends a wavefront diagonal to its maximum reach using Smith-Waterman gap scoring.
 *
 * Performs WaveFront Smith-Waterman-Gotoh alignment of two strings, returning the
 * farthest-reaching truth index reachable at a cost at or below max_score. Every wavefront
 * is folded into the running maximum, so the result is the best reach over all diagonals and
 * all scores up to max_score, and is therefore non-decreasing in max_score.
 *
 * @param[in] query The query sequence.
 * @param[in] truth The truth sequence.
 * @param[in,out] offs Pre-allocated offset array used to track wavefront progress.
 * @param[in] main_diag Main diagonal index constraining diagonal reference transitions.
 * @param[in] main_diag_start Starting offset on the main diagonal.
 * @param[in] max_score Maximum allowed alignment score.
 * @param[in] x Substitution penalty.
 * @param[in] o Gap-open penalty.
 * @param[in] e Gap-extension penalty.
 * @param[in] print Whether to enable debug printing.
 * @param[in] reverse Whether to run the reverse variant of the alignment algorithm.
 * @return Farthest-reaching truth index reachable within max_score, or 0 if either sequence is
 *   empty, since no truth index is reachable then.
 */
int wf_swg_max_reach(
        const std::string & query, const std::string & truth,
        std::vector<int> & offs,
        int main_diag, int main_diag_start, int max_score,
        int x, int o, int e, bool print /* false */, bool reverse /* false */
        ) {

    // init
    int query_len = query.size();
    int truth_len = truth.size();

    // early exit if either string is empty, since then no truth index is reachable
    if (!query_len || !truth_len) return 0;

    int mat_len = query_len + truth_len - 1;
    int main_diag_off = main_diag_start - main_diag;
    int s = 0;
    int s2 = 0;
    int scores = std::max(x, o+e)+1;
    int max_reach = 0;
    ReachOffsets offs_at(offs, scores, mat_len);
    offs_at(MAT_SUB, s2, query_len-1) = -1;

    while (true) {

        // EXTEND WAVEFRONT (leave INS, DEL forwards)
        if (!reverse) for (mat_t m : {MAT_INS, MAT_DEL}) {
            for (int d = 0; d < mat_len; d++) {
                int off = offs_at(m, s2, d);
                int diag = d + 1 - query_len;

                if (off >= 0 && off < query_len &&
                        diag+off >= 0 && diag+off < truth_len &&
                        off >= offs_at(MAT_SUB, s2, d)) {
                    offs_at(MAT_SUB, s2, d) = off;
                    if(print) printf("(S, %d, %d) swap fwd\n", off, off+diag);

                }
            }
        }

        // EXTEND WAVEFRONT (diag, SUB only)
        for (int d = 0; d < mat_len; d++) {
            int off = offs_at(MAT_SUB, s2, d);
            int diag = d + 1 - query_len;

            // extend
            while ( (diag != main_diag || off+1 < main_diag_off) &&
                        off != -2 && diag + off >= -1 && 
                        off < query_len - 1 && 
                        diag + off < truth_len - 1) {
                if (query[off+1] == truth[diag+off+1]) off++;
                else break;
            }
            if (off > offs_at(MAT_SUB, s2, d))
                if(print) printf("(S, %d, %d) extend\n", off, off+diag);
            offs_at(MAT_SUB, s2, d) = off;

            // finish if we've reached the last column, the largest reach possible
            if (off + diag == truth_len - 1) {
                return truth_len-1;
            }

        }

        // fold this wavefront into the running maximum before its buffer row is recycled
        for (mat_t m : EnumRange<mat_t, MAT_SLOTS>{}) {
            for (int d = 0; d < mat_len; d++) {
                int off = offs_at(m, s2, d);
                int diag = d + 1 - query_len;
                if (off >= 0 && off < query_len &&
                        diag+off >= 0 && diag+off < truth_len)
                    max_reach = std::max(max_reach, diag + off);
            }
        }
        if (s == max_score) break;

        /* if (print) for (mat_t mi : EnumRange<mat_t, MAT_SLOTS>{}) { */
        /*     printf("\n%s matrix\n", type_strs[mat_to_edittype(mi)].data()); */
        /*     printf("offs %d:", s); */
        /*     for (int di = 0; di < int(query.size() + truth.size()-1); di++) { */
        /*         printf("\t%d", offs[mi*z + s2*y + di]); */
        /*     } */
        /*     printf("\n"); */
        /* } */

        // NEXT WAVEFRONT
        s++; s2++;
        if (s2 == scores) s2 = 0;
        // init new row to all invalid
        for (mat_t m : {MAT_INS, MAT_DEL}) {
            for (int d = 0; d < mat_len; d++) {
                offs_at(m, s2, d) = -2;
            }
        }
        if (print) printf("\nscore = %d\n", s);

        for (int d = 0; d < mat_len; d++) {
            int diag = d + 1 - query_len;

            // sub (in SUB)
            int p = s - x;
            int p2 = s2 - x;
            if (p2 < 0) p2 += scores;
            if (p >= 0 && offs_at(MAT_SUB, p2, d) != -2 && 
                            offs_at(MAT_SUB, p2, d)+1 < query_len &&
                     diag + offs_at(MAT_SUB, p2, d)+1 < truth_len &&
                            offs_at(MAT_SUB, p2, d)+1 >= offs_at(MAT_SUB, s2, d)) {
                offs_at(MAT_SUB, s2, d) = offs_at(MAT_SUB, p2, d) + 1;
                if(print) printf("(S, %d, %d) sub\n", offs_at(MAT_SUB, s2, d), 
                        offs_at(MAT_SUB, s2, d)+diag);
            }

            // open gap (enter DEL, open fwd only)
            p = reverse ? s - e : s - (o+e);
            p2 = reverse ? s2 - e : s2 - (o+e);
            if (p2 < 0) p2 += scores;
            if (p >= 0 && d > 0 && 
                           offs_at(MAT_SUB, p2, d-1) != -2 &&
                    diag + offs_at(MAT_SUB, p2, d-1) < truth_len &&
                           offs_at(MAT_SUB, p2, d-1) >= offs_at(MAT_DEL, s2, d)) {
                offs_at(MAT_DEL, s2, d) = offs_at(MAT_SUB, p2, d-1);
                if(print) printf("(D, %d, %d) open\n", offs_at(MAT_DEL, s2, d), 
                        offs_at(MAT_DEL, s2, d)+diag);
            }
            // open gap (enter INS, open fwd only)
            if (p >= 0 && d < mat_len-1 && 
                           offs_at(MAT_SUB, p2, d+1) != -2 &&
                           offs_at(MAT_SUB, p2, d+1)+1 < query_len &&
                    diag + offs_at(MAT_SUB, p2, d+1)+1 < truth_len &&
                    diag + offs_at(MAT_SUB, p2, d+1)+1 >= 0 &&
                           offs_at(MAT_SUB, p2, d+1)+1 >= offs_at(MAT_INS, s2, d)) {
                offs_at(MAT_INS, s2, d) = offs_at(MAT_SUB, p2, d+1)+1;
                if(print) printf("(I, %d, %d) open\n", offs_at(MAT_INS, s2, d), 
                        offs_at(MAT_INS, s2, d)+diag);
            }

            // leave INDEL (open rev only)
            p = s - o;
            p2 = s2 - o;
            if (p2 < 0) p2 += scores;
            if (reverse && p >= 0) {
                for (mat_t m : {MAT_INS, MAT_DEL}) {
                    if (        offs_at(m, p2, d) >= 0 && 
                                offs_at(m, p2, d) < query_len &&
                         diag + offs_at(m, p2, d) >= 0 && 
                         diag + offs_at(m, p2, d) < truth_len &&
                                offs_at(m, p2, d) > offs_at(MAT_SUB, s2, d)) {
                        offs_at(MAT_SUB, s2, d) = offs_at(m, p2, d);
                        if(print) printf("(S, %d, %d) swap rev\n", 
                                offs_at(m, p2, d), diag+offs_at(m, p2, d));
                    }
                }
            }

            // extend gap (stay DEL)
            p = s - e;
            p2 = s2 - e;
            if (p2 < 0) p2 += scores;
            if (p >= 0 && d > 0 && 
                           offs_at(MAT_DEL, p2, d-1) != -2 &&
                    diag + offs_at(MAT_DEL, p2, d-1) < truth_len &&
                           offs_at(MAT_DEL, p2, d-1) >= offs_at(MAT_DEL, s2, d)) {
                offs_at(MAT_DEL, s2, d) = offs_at(MAT_DEL, p2, d-1);
                if(print) printf("(D, %d, %d) extend\n", offs_at(MAT_DEL, s2, d), 
                        offs_at(MAT_DEL, s2, d)+diag);
            }
            // extend gap (stay INS)
            if (p >= 0 && d < mat_len-1 && 
                           offs_at(MAT_INS, p2, d+1) != -2 &&
                           offs_at(MAT_INS, p2, d+1)+1 < query_len &&
                    diag + offs_at(MAT_INS, p2, d+1)+1 < truth_len &&
                    diag + offs_at(MAT_INS, p2, d+1)+1 >= 0 &&
                           offs_at(MAT_INS, p2, d+1)+1 >= offs_at(MAT_INS, s2, d)) {
                offs_at(MAT_INS, s2, d) = offs_at(MAT_INS, p2, d+1)+1;
                if(print) printf("(I, %d, %d) extend\n", offs_at(MAT_INS, s2, d), 
                        offs_at(MAT_INS, s2, d)+diag);
            }
        }
    } // end reach

    return max_reach;
}

/**************************************************************************************************/

/**
 * @brief Computes the edit distance between two sequences using wavefront alignment.
 *
 * @param[in] query The query sequence.
 * @param[in] truth The truth sequence.
 * @param[out] s Output variable set to the edit distance.
 * @param[in] print Whether to enable debug printing.
 */
void wf_ed(const std::string & query, const std::string & truth, int & s, bool print) {

    // alignment
    int query_len = query.size();
    int truth_len = truth.size();

    // early exit if either string is empty
    if (!query_len) { s = truth_len; return; }
    if (!truth_len) { s = query_len; return; }
    s = 0;

    int mat_len = query_len + truth_len - 1;
    std::vector< std::vector<int> > offs;
    offs.push_back(std::vector<int>(mat_len, -2));
    offs[0][query_len-1] = -1;
    bool done = false;
    while (true) {

        // EXTEND WAVEFRONT
        for (int d = 0; d < mat_len; d++) {
            int off = offs[s][d];
            int diag = d + 1 - query_len;

            // don't allow starting from untouched cells
            if (off == -2) continue;

            // check that it's within matrix
            if (diag + off + 1 < 0) continue;
            if (off > query_len - 1) continue;
            if (diag + off > truth_len - 1) continue;

            // extend
            while (off < query_len - 1 &&
                   diag + off < truth_len - 1) {
                if (query[off+1] == truth[diag+off+1]) off++;
                else break;
            }
            if (off > offs[s][d])
                if(print) printf("(%d, %d) extend\n", off, off+diag);
            offs[s][d] = off;

            // finish if done
            if (off == query_len - 1 && off + diag == truth_len - 1)
            { done = true; break; }

        }
        if (done) break;

        // debug print
        if(print) printf("offs %d:", s);
        for (int di = 0; di < int(query.size() + truth.size()-1); di++) {
            if(print) printf("\t%d", offs[s][di]);
        }
        if(print) printf("\n");

        // NEXT WAVEFRONT
        offs.push_back(std::vector<int>(mat_len, -2));
        s++;
        if(print) printf("\nscore = %d\n", s);
        for (int d = 0; d < mat_len; d++) {
            int diag = d + 1 - query_len;

            // SUB
            if (s-1 >= 0 && offs[s-1][d] != -2 &&
                            offs[s-1][d]+1 < query_len &&
                     diag + offs[s-1][d]+1 < truth_len &&
                            offs[s-1][d]+1 >= offs[s][d]) {
                offs[s][d] = offs[s-1][d] + 1;
                if(print) printf("(%d, %d) sub\n", offs[s][d], offs[s][d]+diag);
            }

            // DEL
            if (s-1 >= 0 && d > 0 &&
                           offs[s-1][d-1] != -2 &&
                    diag + offs[s-1][d-1] < truth_len &&
                           offs[s-1][d-1] >= offs[s][d]) {
                offs[s][d] = offs[s-1][d-1];
                if(print) printf("(%d, %d) del\n", offs[s][d], offs[s][d]+diag);
            }

            // INS
            if (s-1 >= 0 && d < mat_len-1 &&
                           offs[s-1][d+1] != -2 &&
                           offs[s-1][d+1]+1 < query_len &&
                    diag + offs[s-1][d+1]+1 < truth_len &&
                    diag + offs[s-1][d+1]+1 >= -1 &&
                           offs[s-1][d+1]+1 >= offs[s][d]) {
                offs[s][d] = offs[s-1][d+1]+1;
                if(print) printf("(%d, %d) ins\n", offs[s][d], offs[s][d]+diag);
            }
        }
    }
}

