#!/bin/bash

    # -b ../r10.4_chr20/ont-case-study/input/data/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed \
    # ../test/calls.vcf.gz \
    # ../test/truth.vcf.gz \
./vcfdist \
    ../out/truth.vcf.gz \
    ../out/orig_truth.vcf.gz \
    /x/gm24385/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta \
    -b ../scripts/data/all_20.bed \
    -o ../out/ \
    -g 50
