#!/bin/bash

source ../pipeline/includes.sh

sub_id="K4GT3"

time ./vcfdist \
    $data/pfda-v2/phased_vcfs/GRCh38/${sub_id}_HG002_O.vcf.gz \
    $data/nist-v4.2.1/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark_phased.vcf.gz \
    $data/refs/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta \
    -b $data/nist-v4.2.1/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed \
    -p ../out/test_
