name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: install htslib
      run: |
       sudo apt-get update
       sudo apt-get install -y libbz2-dev liblzma-dev
       wget https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
       tar -xvf htslib-1.17.tar.bz2
       cd htslib-1.17
       ./configure --prefix=`pwd`
       make
       make install
       echo LIBRARY_PATH=`pwd`:$LIBRARY_PATH >> $GITHUB_ENV
       echo LD_LIBRARY_PATH=`pwd`:$LD_LIBRARY_PATH >> $GITHUB_ENV
    - name: make vcfdist
      run: |
       cp -r htslib-1.17/htslib src
       echo $LIBRARY_PATH
       echo $LD_LIBRARY_PATH
       cd src
       make
       ./vcfdist -v
