name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install htslib
    - run: |
       wget https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
       tar -xvf htslib-1.17.tar.bz2
       cd htslib-1.17
       ./configure --prefix=/usr/local
       make
       make install
       export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    - name: make vcfdist
      run: cd ../src && make
