name: Tests

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  HTSLIB_VERSION: "1.17"

jobs:
  Tests:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v7
      with:
        ref: ${{ github.ref }}
    - name: Install build dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y libbz2-dev liblzma-dev libgtest-dev
    - name: Cache htslib
      id: cache-htslib
      uses: actions/cache@v6
      with:
        path: htslib-${{ env.HTSLIB_VERSION }}
        key: htslib-${{ env.HTSLIB_VERSION }}-${{ runner.os }}-${{ runner.arch }}
    - name: Build htslib
      if: steps.cache-htslib.outputs.cache-hit != 'true'
      run: |
       wget https://github.com/samtools/htslib/releases/download/${HTSLIB_VERSION}/htslib-${HTSLIB_VERSION}.tar.bz2
       tar -xf htslib-${HTSLIB_VERSION}.tar.bz2
       cd htslib-${HTSLIB_VERSION}
       ./configure --prefix=`pwd`
       make -j$(nproc)
       make install
    - name: Set htslib paths
      run: |
       echo LIBRARY_PATH=$PWD/htslib-${HTSLIB_VERSION}:$LIBRARY_PATH >> $GITHUB_ENV
       echo LD_LIBRARY_PATH=$PWD/htslib-${HTSLIB_VERSION}:$LD_LIBRARY_PATH >> $GITHUB_ENV
    - name: Make vcfdist
      run: |
       cp -r htslib-${HTSLIB_VERSION}/htslib src
       cd src
       make -j$(nproc)
       ./vcfdist -v
    - name: Make unit tests
      run: |
       cd tests/unit/build
       make -j$(nproc)
    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0
    - name: Test vcfdist
      env:
        VCFDIST_SKIP_BUILD: "1"
      run: |
       uv venv
       uv pip install pytest pytest-workflow
       cd tests
       ../.venv/bin/pytest -vv
