name: test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install htslib
      run: |
       wget https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
       tar -xvf htslib-1.17.tar.bz2
       cd htslib-1.17
       ./configure --prefix=`pwd`
       make
       make install
       echo LIBRARY_PATH=`pwd`:$LIBRARY_PATH >> $GITHUB_ENV
       echo LD_LIBRARY_PATH=`pwd`:$LD_LIBRARY_PATH >> $GITHUB_ENV
    - name: make vcfdist
      run: |
       cp -r htslib-1.17/htslib src
       echo $LIBRARY_PATH
       echo $LD_LIBRARY_PATH
       cd src
       make
       ./vcfdist -v
    - name: test vcfdist
      run: |
       cd tests
       make
       ./test_vcfdist
